directories:
  output: release/
  buildResources: build
productName: Edixo
appId: com.sevens.edixo
files:
  - dist/electron/**/*
  - node_modules/
  - package.json
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
mac:
  icon: build/icons/icon.icns
win:
  icon: build/icons/icon.ico
linux:
  icon: build/icons
electronVersion: 2.0.11
